version: '3'
services:
  build-service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./bin:/disco-ii-cortex-m7-scheduler/bin
      - ./include:/disco-ii-cortex-m7-scheduler/include
      - ./lib:/disco-ii-cortex-m7-scheduler/lib
      - ./src:/tmp-src
